# service base names — "-oidc-azure" is appended to each
documents-generator
booking-portal-client
skycenter-client
skycore-backend
booking-portal-backend
openapi-consolidator
temperature-simulation
skygate-backend
skynet-client
