# env_name  vault_addr
dev   http://vault.dev.skycell.local
test  http://vault.test.skycell.local
demo  http://vault.demo.skycell.local
poc   http://vault.poc.skycell.local
pre   http://vault.pre.skycell.local
prod  http://vault.prod.skycell.local
